worker_processes 1;

error_log logs/error.log warn;
pid logs/nginx.pid;

events {
    worker_connections 1024;
}

http {
    include /opt/homebrew/etc/nginx/mime.types;

    sendfile on;
    tcp_nopush on;
    keepalive_timeout 65;
    client_max_body_size 0;

    types {
        video/x-matroska mkv;
        audio/flac flac;
        audio/wav wav;
        audio/aac aac;
    }

    server {
        listen 8001;
        server_name localhost;

        root /Users/vahan/src/mutr-web/web/dist;

        location / {
            try_files $uri $uri/ /index.html;
        }

        location /media/ {
            alias /Users/vahan/src/mutr-web/server/data/projects/;
            sendfile on;
            tcp_nopush on;
            add_header Accept-Ranges bytes;
        }

        location /api/ {
            proxy_pass http://127.0.0.1:8000;
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_buffering off;
            proxy_read_timeout 3600s;
            proxy_send_timeout 3600s;
        }
    }
}
